// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCEkeFN4PO7F1ey94AP6DhbBEl_w9H1q8o',
    appId: '1:1047359742947:web:c3520c63c912664785f6d6',
    messagingSenderId: '1047359742947',
    projectId: 'safe-bite-production',
    authDomain: 'safe-bite-production.firebaseapp.com',
    storageBucket: 'safe-bite-production.firebasestorage.app',
    measurementId: 'G-44JXRHK6FH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCe4i54DiEB-jKy9MwU6b5pmmuAt27CyWA',
    appId: '1:1047359742947:android:b96df3d0a8c6ba9985f6d6',
    messagingSenderId: '1047359742947',
    projectId: 'safe-bite-production',
    storageBucket: 'safe-bite-production.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyApsxWCwpjryDxykPu_Be3H2uKuDYWMy24',
    appId: '1:1047359742947:ios:50ebbc678d41bd7585f6d6',
    messagingSenderId: '1047359742947',
    projectId: 'safe-bite-production',
    storageBucket: 'safe-bite-production.firebasestorage.app',
    iosBundleId: 'com.example.safeBite',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyApsxWCwpjryDxykPu_Be3H2uKuDYWMy24',
    appId: '1:1047359742947:ios:50ebbc678d41bd7585f6d6',
    messagingSenderId: '1047359742947',
    projectId: 'safe-bite-production',
    storageBucket: 'safe-bite-production.firebasestorage.app',
    iosBundleId: 'com.example.safeBite',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCEkeFN4PO7F1ey94AP6DhbBEl_w9H1q8o',
    appId: '1:1047359742947:web:159ba6fc7d0e35fe85f6d6',
    messagingSenderId: '1047359742947',
    projectId: 'safe-bite-production',
    authDomain: 'safe-bite-production.firebaseapp.com',
    storageBucket: 'safe-bite-production.firebasestorage.app',
    measurementId: 'G-4DVGJT7Z0E',
  );

}